### ISSUE TITLE
Relative path to image files

### ISSUE THREAD

**Issue by martinhansdk** [bauripalash/tkhtmlview#45]
Given the following directory structure:

```
script.py
help/feature.html
help/feature/images/diagram.png
```

If `help/feature.html` contains the following:

```
<html>
    Here is an image:

    <img src="images/diagram.png">
</html>
```

and `script.py` contains this:

```
from tkinter import Tk
from tkhtmlview import HTMLLabel, RenderHTML


root = Tk()

label = HTMLLabel(root, html=RenderHTML('help/feature.html'))
label.pack()

root.mainloop()
```

then I would have expected the image to be shown in the GUI. However, it only shows up if the `src` attribute in the in the `img` tag is changed to contain the absolute path to the PNG file.

Support for image file names that are relative to the HTML document would be useful and more consistent with how browsers handle it.

**Comment by bauripalash** [comment]
I see,
the problem is, you're running the script from root directory. From which the diagram.png image is in `/help/feature/images/diagram.png` path, but your HTML is looking for the image in `/images/diagram.png` which doesn't exists.

**Comment by martinhansdk** [comment]
Exactly, the current implementation looks for the image relative to the current directory, but according to https://www.w3schools.com/html/html_filepaths.asp `images/diagram.png` (no initial slash) means relative to the HTML document.

**Comment by martinhansdk** [comment]
The standard library function [urllib.parse.urljoin](https://docs.python.org/3.11/library/urllib.parse.html#urlparse.urljoin) (python 2: [urlparse.urljoin](https://docs.python.org/2/library/urlparse.html#urlparse.urljoin) ) does exactly this. It works on both local paths and urls:

```
>>> from urllib.parse import urljoin
>>> urljoin('local.html', 'images/diagram.png')
'images/diagram.png'
>>> urljoin('http://example.com/help/doc.html', 'images/diagram.png') 
'http://example.com/help/images/diagram.png'
>>> urljoin('http://example.com/help/doc.html', '/images/diagram.png') 
'http://example.com/images/diagram.png'
```

**Comment by bauripalash** [comment]
You see the problem is, tkhtmlview isn't a web engine, it doesn't even support the whole html specification.

In tkhtmlview there's no concept of html files, the RenderHTML function just reads the file and feeds the string to the library, the core doesn't know anything about html files, thus making the above mentioned functionality relatively impossible.

Think RenderHTML as an wrapper for `open(..)`, 

https://github.com/bauripalash/tkhtmlview/blob/b8b406f27af90871948d889dfc537662f0f955f1/tkhtmlview/utils.py#L10

The library is very primitive, you give it a string, it gives you a tkinter widget, nothing less, nothing more.
