### ISSUE TITLE
How to make a link open in the same document.

### ISSUE THREAD

**Issue by onekk** [bauripalash/tkhtmlview#6]
Hi and thanks for this piece of code:

I'm facing this problem, I want to use your code into another program to make an html help page for the program.

So I''ve done some text with the usual html tags:

```
 <ul>
  <li> <a href="#section2">Go to Section 2</a></li>
```

and the anchor text

```
<h3>CAM buttons</h3>
<a name="section2"> </a> 
```

But it open a new link in browser and not jump to the `<a name=...`  tags

Best Regards

Carlo D.

**Comment by bauripalash** [comment]
I don't think that's possible for now.

**Comment by onekk** [comment]
Ok thanks

**Comment by lafkpages** [comment]
I managed to make it call a function when you press a link instead of opening it with the `webbrowser.open()` method.
In line `190`, change the `__init__` function to:
```
def __init__(self, w, tag_name, url, callback=None):
        #------------------------------------------------------------------------------------------
        self._w       = w
        self.tag_name = tag_name
        self.URL      = url
        self.callback = webbrowser.open
        
        if not callback == None:
            self.callback = callback
```
**(Note the `callback=None`, `self.callback = webbrowser.open` and `if` statement)**

And after all the imports (aproximately line `14`) I added: 
`link_callback = None`

and then in the `def _w_tags_apply_all(self)` function (aprox line `675`), I added:
`global link_callback`, and changed:

`self.hlink_slots.append(HLinkSlot(self._w, key, tag[Bind.KEY][Bind.LINK]))`
to:
`self.hlink_slots.append(HLinkSlot(self._w, key, tag[Bind.KEY][Bind.LINK], link_callback))`

Then all you have to do is change the global function `link_callback` and it will be run. If you leave it as `None` it will call `webbrowser.open` method.
